name: recipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0  # Adjusted to a version compatible with Dart 3.2+

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0  # Adjusted to version compatible with Dart 3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/beef-tacos.jpg
    - assets/images/chocolate-cookies.jpg
    - assets/images/greek-salad.jpg
    - assets/images/images.jpeg
    - assets/images/margherita-pizza.jpg
    - assets/images/pancakes.jpg
    - assets/images/pasta-carbonara.jpg
    - assets/images/veggie-stir-fry.jpg


